handlers=java.util.logging.ConsoleHandler
.level=INFO

java.util.logging.ConsoleHandler.level=ALL
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

jpa.level=ALL
org.hibernate.level=WARNING
org.hibernate.tool.schema.level=WARNING
org.hibernate.engine.jdbc.spi.SqlExceptionHelper.level=SEVERE
org.jboss.resteasy.level=WARNING
